import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { formatDateIN, inr, methodLabel } from "@/lib/rent/months";
import { escapeHtml, printHtml } from "@/lib/rent/print";
import type { Building, Payment } from "@/lib/rent/types";

export function BillDialog({
  payment,
  building,
  open,
  onOpenChange,
}: {
  payment: Payment | null;
  building?: Building | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const buildingName = building?.name || "Rentweb";
  const owner = building?.ownerName || "";
  const baseRent = payment ? payment.totalRent - payment.extraAmount : 0;

  function printBill() {
    if (!payment) return;
    printHtml(
      `Bill ${payment.month} ${payment.roomNumber}`,
      `<div class="sheet">
        <p class="kicker">Rent bill</p>
        <h1>${escapeHtml(buildingName)}</h1>
        <p class="muted">${escapeHtml(building?.address || "")}</p>
        <p class="muted">${escapeHtml(building?.phone || "")}</p>
        <hr />
        ${row("Bill to", payment.tenantName ?? "—")}
        ${row("Room", payment.roomNumber)}
        ${row("Month", payment.month)}
        ${row("Rent", inr(baseRent))}
        ${payment.extraAmount > 0 ? row(`Extra${payment.extraNote ? ` · ${payment.extraNote}` : ""}`, inr(payment.extraAmount)) : ""}
        ${row("Total billed", inr(payment.totalRent))}
        ${row("Received", inr(payment.paidAmount))}
        ${row("Balance due", inr(payment.remainingAmount))}
        ${row("Status", payment.status)}
        ${payment.paidBy ? row("Last method", methodLabel(payment.paidBy)) : ""}
        ${row("Date", formatDateIN(new Date()))}
        <div class="foot"><span>${escapeHtml(owner ? `Issued by ${owner}` : "Generated by Rentweb")}</span><span>Pay cash, UPI or card</span></div>
      </div>`,
    );
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="print-host">
        <DialogTitle className="no-print">Rent bill</DialogTitle>
        <DialogDescription className="no-print">Invoice for {payment?.month}</DialogDescription>
        {payment && (
          <div className="print-sheet mt-4 rounded-2xl border border-border bg-bg p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="font-display text-2xl tracking-tight">{buildingName}</p>
                {building?.address ? <p className="mt-1 text-xs text-muted">{building.address}</p> : null}
                {building?.phone ? <p className="text-xs text-muted">{building.phone}</p> : null}
              </div>
              <p className="text-xs font-medium tracking-[0.16em] text-muted uppercase">Bill</p>
            </div>
            <div className="my-4 h-px bg-border" />
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted">Bill to</dt>
              <dd className="text-right">{payment.tenantName ?? "—"}</dd>
              <dt className="text-muted">Room</dt>
              <dd className="text-right">{payment.roomNumber}</dd>
              <dt className="text-muted">Month</dt>
              <dd className="text-right">{payment.month}</dd>
              <dt className="text-muted">Rent</dt>
              <dd className="text-right tabular">{inr(baseRent)}</dd>
              {payment.extraAmount > 0 ? (
                <>
                  <dt className="text-muted">Extra{payment.extraNote ? ` · ${payment.extraNote}` : ""}</dt>
                  <dd className="text-right tabular">{inr(payment.extraAmount)}</dd>
                </>
              ) : null}
              <dt className="text-muted">Total billed</dt>
              <dd className="text-right tabular font-medium">{inr(payment.totalRent)}</dd>
              <dt className="text-muted">Received</dt>
              <dd className="text-right tabular">{inr(payment.paidAmount)}</dd>
              <dt className="text-muted">Balance due</dt>
              <dd className="text-right tabular font-medium">{inr(payment.remainingAmount)}</dd>
              <dt className="text-muted">Status</dt>
              <dd className="text-right capitalize">{payment.status}</dd>
              <dt className="text-muted">Date</dt>
              <dd className="text-right">{formatDateIN(new Date())}</dd>
            </dl>
          </div>
        )}
        <Button className="no-print mt-4 w-full" variant="secondary" type="button" onClick={printBill}>
          <Printer className="size-4" />
          Print bill
        </Button>
      </DialogContent>
    </Dialog>
  );
}

function row(k: string, v: string): string {
  return `<div class="row"><span>${escapeHtml(k)}</span><b>${escapeHtml(v)}</b></div>`;
}
