import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { formatDateIN, inr, methodLabel } from "@/lib/rent/months";
import type { Building, Payment } from "@/lib/rent/types";

export function BillDialog({
  payment,
  building,
  open,
  onOpenChange,
}: {
  payment: Payment | null;
  building?: Building | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const buildingName = building?.name || "Rentweb";
  const owner = building?.ownerName || "";
  const baseRent = payment ? payment.totalRent - payment.extraAmount : 0;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="print:static print:w-full print:max-w-none print:border-0 print:bg-white print:p-0 print:text-black print:shadow-none">
        <DialogTitle className="print:hidden">Rent bill</DialogTitle>
        <DialogDescription className="print:hidden">
          Invoice for {payment?.month}
        </DialogDescription>
        {payment && (
          <div className="mt-4 rounded-2xl border border-border bg-bg p-5 print:border-black print:bg-white">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="font-display text-2xl tracking-tight">{buildingName}</p>
                {building?.address ? (
                  <p className="mt-1 text-xs text-muted print:text-neutral-600">{building.address}</p>
                ) : null}
                {building?.phone ? (
                  <p className="text-xs text-muted print:text-neutral-600">{building.phone}</p>
                ) : null}
              </div>
              <p className="text-xs font-medium tracking-[0.16em] text-muted uppercase print:text-neutral-600">
                Bill
              </p>
            </div>
            <div className="my-4 h-px bg-border print:bg-neutral-300" />
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted">Bill to</dt>
              <dd className="text-right">{payment.tenantName ?? "—"}</dd>
              <dt className="text-muted">Room</dt>
              <dd className="text-right">{payment.roomNumber}</dd>
              <dt className="text-muted">Month</dt>
              <dd className="text-right">{payment.month}</dd>
              <dt className="text-muted">Rent</dt>
              <dd className="text-right tabular">{inr(baseRent)}</dd>
              {payment.extraAmount > 0 ? (
                <>
                  <dt className="text-muted">
                    Extra{payment.extraNote ? ` · ${payment.extraNote}` : ""}
                  </dt>
                  <dd className="text-right tabular">{inr(payment.extraAmount)}</dd>
                </>
              ) : null}
              <dt className="text-muted">Total</dt>
              <dd className="text-right tabular font-medium">{inr(payment.totalRent)}</dd>
              <dt className="text-muted">Received</dt>
              <dd className="text-right tabular">{inr(payment.paidAmount)}</dd>
              <dt className="text-muted">Balance due</dt>
              <dd className="text-right tabular font-medium">{inr(payment.remainingAmount)}</dd>
              <dt className="text-muted">Status</dt>
              <dd className="text-right capitalize">{payment.status}</dd>
              {payment.paidBy ? (
                <>
                  <dt className="text-muted">Last method</dt>
                  <dd className="text-right">{methodLabel(payment.paidBy)}</dd>
                </>
              ) : null}
              <dt className="text-muted">Date</dt>
              <dd className="text-right">{formatDateIN(new Date())}</dd>
            </dl>
            <div className="mt-8 flex justify-between text-xs text-muted print:text-neutral-600">
              <span>{owner ? `Issued by ${owner}` : "Generated by Rentweb"}</span>
              <span>Pay cash, UPI, or card</span>
            </div>
          </div>
        )}
        <Button
          className="mt-4 w-full print:hidden"
          variant="secondary"
          type="button"
          onClick={() => window.print()}
        >
          <Printer className="size-4" />
          Print bill
        </Button>
      </DialogContent>
    </Dialog>
  );
}
