import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { formatDateTimeIN, inr, methodLabel } from "@/lib/rent/months";
import { escapeHtml, printHtml } from "@/lib/rent/print";
import type { Building, Payment, PaymentEvent } from "@/lib/rent/types";

export function ReceiptDialog({
  payment,
  event,
  building,
  open,
  onOpenChange,
}: {
  payment: Payment | null;
  event?: PaymentEvent | null;
  building?: Building | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const buildingName = building?.name || "Rentweb";
  const owner = building?.ownerName || "";
  const paidNow = event?.amount ?? payment?.paidAmount ?? 0;
  const method = event?.method ?? payment?.paidBy ?? "";
  const when = event?.createdAt ?? payment?.paidAt;
  const utr = event?.reference || payment?.transactionId || "—";

  function printReceipt() {
    if (!payment) return;
    printHtml(
      `Receipt ${payment.month} ${payment.roomNumber}`,
      `<div class="sheet">
        <p class="kicker">Payment receipt</p>
        <h1>${escapeHtml(buildingName)}</h1>
        <p class="muted">${escapeHtml(building?.address || "")}</p>
        <hr />
        ${row("Tenant", payment.tenantName ?? "—")}
        ${row("Room", payment.roomNumber)}
        ${row("Month", payment.month)}
        ${row("Billed amount", inr(payment.totalRent))}
        ${row("Paid this receipt", inr(paidNow))}
        ${row("Total paid so far", inr(payment.paidAmount))}
        ${row("Balance due", inr(payment.remainingAmount))}
        ${row("Method", methodLabel(method))}
        ${row("Date & time", formatDateTimeIN(when))}
        ${row("UTR / Txn ID", utr)}
        <div class="foot"><span>${escapeHtml(owner ? `Received by ${owner}` : "Generated by Rentweb")}</span><span>Authorized</span></div>
      </div>`,
    );
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="print-host">
        <DialogTitle className="no-print">Rent receipt</DialogTitle>
        <DialogDescription className="no-print">Slip for {payment?.month}</DialogDescription>
        {payment && (
          <div className="print-sheet mt-4 rounded-2xl border border-border bg-bg p-5">
            <p className="font-display text-2xl tracking-tight">{buildingName}</p>
            {building?.address ? <p className="mt-1 text-xs text-muted">{building.address}</p> : null}
            <p className="mt-1 text-xs text-muted">Payment receipt</p>
            <div className="my-4 h-px bg-border" />
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted">Tenant</dt>
              <dd className="text-right">{payment.tenantName ?? "—"}</dd>
              <dt className="text-muted">Room</dt>
              <dd className="text-right">{payment.roomNumber}</dd>
              <dt className="text-muted">Month</dt>
              <dd className="text-right">{payment.month}</dd>
              <dt className="text-muted">Billed</dt>
              <dd className="text-right tabular">{inr(payment.totalRent)}</dd>
              <dt className="text-muted">Paid now</dt>
              <dd className="text-right tabular font-medium">{inr(paidNow)}</dd>
              <dt className="text-muted">Total paid</dt>
              <dd className="text-right tabular">{inr(payment.paidAmount)}</dd>
              <dt className="text-muted">Still due</dt>
              <dd className="text-right tabular">{inr(payment.remainingAmount)}</dd>
              <dt className="text-muted">Method</dt>
              <dd className="text-right">{methodLabel(method)}</dd>
              <dt className="text-muted">Date & time</dt>
              <dd className="text-right">{formatDateTimeIN(when)}</dd>
              <dt className="text-muted">UTR / Txn ID</dt>
              <dd className="text-right font-mono text-xs">{utr}</dd>
            </dl>
            <div className="mt-8 flex justify-between text-xs text-muted">
              <span>{owner ? `Received by ${owner}` : "Generated by Rentweb"}</span>
              <span>Authorized</span>
            </div>
          </div>
        )}
        <Button className="no-print mt-4 w-full" variant="secondary" type="button" onClick={printReceipt}>
          <Printer className="size-4" />
          Print receipt
        </Button>
      </DialogContent>
    </Dialog>
  );
}

function row(k: string, v: string): string {
  return `<div class="row"><span>${escapeHtml(k)}</span><b class="${k.includes("UTR") ? "mono" : ""}">${escapeHtml(v)}</b></div>`;
}
