import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { formatDateIN, inr, methodLabel } from "@/lib/rent/months";
import type { Building, Payment } from "@/lib/rent/types";

export function ReceiptDialog({
  payment,
  building,
  open,
  onOpenChange,
}: {
  payment: Payment | null;
  building?: Building | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const buildingName = building?.name || "Rentweb";
  const owner = building?.ownerName || "";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="print:static print:w-full print:max-w-none print:border-0 print:bg-white print:p-0 print:text-black print:shadow-none">
        <DialogTitle className="print:hidden">Rent receipt</DialogTitle>
        <DialogDescription className="print:hidden">
          Slip for {payment?.month}
        </DialogDescription>
        {payment && (
          <div className="mt-4 rounded-2xl border border-border bg-bg p-5 print:border-black print:bg-white">
            <p className="font-display text-2xl tracking-tight">{buildingName}</p>
            {building?.address ? (
              <p className="mt-1 text-xs text-muted print:text-neutral-600">{building.address}</p>
            ) : null}
            <p className="mt-1 text-xs text-muted print:text-neutral-600">Rent receipt</p>
            <div className="my-4 h-px bg-border print:bg-neutral-300" />
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted">Tenant</dt>
              <dd className="text-right">{payment.tenantName ?? "—"}</dd>
              <dt className="text-muted">Room</dt>
              <dd className="text-right">{payment.roomNumber}</dd>
              <dt className="text-muted">Month</dt>
              <dd className="text-right">{payment.month}</dd>
              <dt className="text-muted">Total rent</dt>
              <dd className="text-right tabular">{inr(payment.totalRent)}</dd>
              <dt className="text-muted">Paid</dt>
              <dd className="text-right tabular">{inr(payment.paidAmount)}</dd>
              <dt className="text-muted">Remaining</dt>
              <dd className="text-right tabular">{inr(payment.remainingAmount)}</dd>
              <dt className="text-muted">Status</dt>
              <dd className="text-right capitalize">{payment.status}</dd>
              <dt className="text-muted">Method</dt>
              <dd className="text-right">{methodLabel(payment.paidBy)}</dd>
              <dt className="text-muted">Date</dt>
              <dd className="text-right">{formatDateIN(payment.paidAt)}</dd>
              <dt className="text-muted">Txn / UTR</dt>
              <dd className="text-right font-mono text-xs">{payment.transactionId || "—"}</dd>
            </dl>
            <div className="mt-8 flex justify-between text-xs text-muted print:text-neutral-600">
              <span>{owner ? `Received by ${owner}` : "Generated by Rentweb"}</span>
              <span>Authorized</span>
            </div>
          </div>
        )}
        <Button
          className="mt-4 w-full print:hidden"
          variant="secondary"
          type="button"
          onClick={() => window.print()}
        >
          <Printer className="size-4" />
          Print
        </Button>
      </DialogContent>
    </Dialog>
  );
}
